#!/usr/bin/env ruby
require 'rubygems'
require 'lockfile'

Lockfile('lock', :retries => 0) do
  require File.dirname(__FILE__) + '/../config/boot'
  require File.dirname(__FILE__) + '/../config/environment'

  Subscription.trials_expiring_soon.each do |sub|
    SubscriptionNotifier.deliver_trial_expiring(sub)
  end

  # # Trial subscriptions for which we have payment info.
  # # This will always turn up empty unless we are collecting
  # # payment info when creating an account.
  # Subscription.find_due_trials.each do |sub|
  #   if !sub.charge
  #     SubscriptionNotifier.deliver_charge_failure(sub)
  #   end
  # end

  Subscription.due.each do |sub|
    if !sub.charge
      sub.state = "pending"
      sub.save
      sub.user.access_class = nil
      sub.user.save

      SubscriptionNotifier.deliver_charge_failure(sub)
    end
  end

end
